name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Deno environment
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Run tests
        run: make test
