name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Deno environment
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.0.2
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Upload
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER: ${{ secrets.USER }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: make all
